name: Build and Publish Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build solution
        run: dotnet build -c Release

      - name: Make docu.sh executable
        run: chmod +x ./docu.sh

      - name: Build docu
        run: ./docu.sh
        shell: bash

      - name: Upload docs artifact to GH pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.docsOutput

  deploy:   
    runs-on: ubuntu-latest
    
    needs: build
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
