name: Publish to Nuget

on: workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      
      - name: nuget publish
        env:
            nuget_push: ${{ secrets.NUGET_API_KEY }}
        run: dotnet fsi build.fsx publish
